autoplanner/urls.py
from django.conf.urls import url

from autoplanner import views

__author__ = 'Matthieu Gallet'
app_name = 'autoplanner'
urlpatterns = [
    url(r'^organization/(?P<organization_pk>\d+)/$', views.organization_index, name='organization_index'),

    url(r'^org/(?P<organization_pk>\d+)\.html', views.organization, name='organization'),
    url(r'^org/start/(?P<organization_pk>\d+)\.html', views.schedule_task, name='schedule_start'),
    url(r'^org/cancel/(?P<organization_pk>\d+)\.html', views.cancel_schedule_task, name='cancel_schedule'),
    url(r'^org/ical/(?P<organization_pk>\d+)/all/(?P<title>.*)\.ics', views.generate_ics, name='ical'),
    url(r'^org/ical/(?P<organization_pk>\d+)/agent/(?P<agent_pk>\d+)/(?P<title>.*)\.ics',
        views.generate_ics, name='ical'),
    url(r'^org/ical/(?P<organization_pk>\d+)/cat/(?P<category_pk>\d+)/(?P<title>.*)\.ics',
        views.generate_ics, name='ical'),
    url(r'^tasks/apply_schedule_run/(?P<schedule_run_pk>\d+)\.html', views.apply_schedule_run,
        name='apply_schedule_run'),
]

autoplanner/models.py
import datetime
import random

from django.conf import settings
from django.core.validators import RegexValidator
from django.db import models
from django.db.models import Q
from django.http import HttpRequest
from django.urls import reverse
from django.utils.formats import date_format, time_format
from django.utils.timezone import get_default_timezone
from django.utils.translation import ugettext_lazy as _

API_KEY_VARIABLE = 'api_key'

__author__ = 'Matthieu Gallet'


def default_day_start():
    x = datetime.datetime.now(tz=get_default_timezone())
    return datetime.datetime(year=x.year, month=x.month, day=x.day, hour=0, minute=0, second=0,
                             tzinfo=get_default_timezone())


def default_day_end():
    return default_day_start() + datetime.timedelta(hours=23, minutes=59, seconds=59)


def default_token(length=64, allowed_chars='abcdefghijklmnopqrstuvwxyz'
                                           'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'):
    # noinspection PyUnusedLocal
    return ''.join([random.choice(allowed_chars) for i in range(length)])


class Organization(models.Model):
    name = models.CharField(_('Name'), db_index=True, max_length=500)
    message = models.CharField(_('Message'), blank=True, max_length=500, default='')
    description = models.TextField(_('Description'), default='', blank=True)
    celery_task_id = models.CharField(_('Celery task id'), db_index=True, max_length=60, blank=True, null=True,
                                      default=None)
    celery_start = models.DateTimeField(_('Celery start'), null=True, blank=True, default=None)
    celery_end = models.DateTimeField(_('Celery end'), null=True, blank=True, default=None)
    access_token = models.CharField(_('Access token'), default=default_token, max_length=300,
                                    validators=[RegexValidator(r'^[a-zA-Z0-9]{1,300}$')])
    max_compute_time = models.PositiveIntegerField(_('Maximum time, in seconds, for finding a solution'),
                                                   default=None, blank=True, null=True,
                                                   help_text=_('Leave it blank if you do not want to set a limit'))
    admins = models.ManyToManyField(settings.AUTH_USER_MODEL, db_index=True, verbose_name=_('Administrators'))
    current_schedule = models.ForeignKey('ScheduleRun', default=None, blank=True, null=True, db_index=True,
                                         related_name='current_organizations', on_delete=models.SET_NULL)

    @classmethod
    def query(cls, request: HttpRequest, readonly=False):
        access_token = ''
        user = getattr(request, 'user')
        if hasattr(request, 'GET'):
            # noinspection PyCallByClass,PyTypeChecker
            access_token = request.GET.get(API_KEY_VARIABLE, '')
        if not user or user.is_anonymous:
            return cls.objects.filter(access_token=access_token)
        # noinspection PyUnresolvedReferences
        elif user.is_superuser:
            return cls.objects.all()
        elif readonly:
            # noinspection PyUnresolvedReferences
            return cls.objects.filter(Q(admins=user) | Q(access_token=access_token))
        # noinspection PyUnresolvedReferences
        return cls.objects.filter(admins=user)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return '%s?%s=%s' % (reverse('organization', kwargs={'organization_pk': self.pk}),
                             API_KEY_VARIABLE, self.access_token)


class ScheduleRun(models.Model):
    organization = models.ForeignKey(Organization, db_index=True, on_delete=models.CASCADE)
    status = models.NullBooleanField(_('Is valid?'), db_index=True, default=None)
    is_selected = models.BooleanField(_('Selected?'), db_index=True, default=False)
    message = models.TextField(_('Result'), max_length=500, default='', blank=True)
    celery_task_id = models.CharField(_('Celery task id'), db_index=True, max_length=60, blank=True, null=True,
                                      default=None)
    celery_start = models.DateTimeField(_('Computation start'), null=True, blank=True, default=None)
    celery_end = models.DateTimeField(_('Computation end'), null=True, blank=True, default=None)
    process_id = models.IntegerField(_('Process ID'), db_index=True, blank=True, null=True, default=None)
    result_dict = models.TextField(_('JSON-serialized result'), blank=True, default=None, null=True)

    def __str__(self):
        end = self.celery_end
        if not end:
            return str(_('Not finished yet.'))
        return '%(d)s, %(t)s' % {'d': date_format(end, use_l10n=True), 't': time_format(end, use_l10n=True)}

    def __unicode__(self):
        return self.__str__()


class OrganizationObject(models.Model):
    organization = models.ForeignKey(Organization, db_index=True, on_delete=models.CASCADE)

    class Meta(object):
        abstract = True

    @classmethod
    def query(cls, request: HttpRequest):
        # noinspection PyUnresolvedReferences
        if request.user.is_superuser:
            return cls.objects.all()
        # noinspection PyUnresolvedReferences
        return cls.objects.filter(organization__admins=request.user)


class Agent(OrganizationObject):
    name = models.CharField(_('Name'), db_index=True, max_length=500)
    start_time = models.DateTimeField(_('Arrival time'), db_index=True, default=None, blank=True, null=True,
                                      help_text=_('Before this date, the agent cannot perform'
                                                  'any task.'))
    end_time = models.DateTimeField(_('Leaving time'), db_index=True, default=None, blank=True, null=True,
                                    help_text=_('After this date, the agent cannot perform any task.'))

    class Meta(object):
        ordering = ('name',)

    def __str__(self):
        return self.name


class Category(OrganizationObject):
    BALANCE_TIME = 'time'
    BALANCE_NUMBER = 'number'
    name = models.CharField(_('Name'), db_index=True, max_length=500)
    balancing_mode = models.CharField(_('Balancing mode'),
                                      max_length=10, choices=((None, _('No balancing')),
                                                              (BALANCE_TIME, _('Total task time')),
                                                              (BALANCE_NUMBER, _('Total task number'))),
                                      blank=True, null=True, default=None)
    balancing_tolerance = models.FloatField(_('Tolerance for balancing the total duration (in seconds)|tasks '
                                              'across agents'), default=0., blank=True, null=True)
    auto_affinity = models.FloatField(_('Affinity for allocating successive tasks of the same category '
                                        'to the same agent'), default=0., blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Category of tasks')
        verbose_name_plural = _('Categories of tasks')

    @property
    def balancing_tolerance_as_timedelta_2(self):
        return datetime.timedelta(seconds=(self.balancing_tolerance or 0))

    @property
    def balancing_tolerance_2(self):
        return self.balancing_tolerance or 0


class MaxAffectation(OrganizationObject):
    MINIMUM = 'min'
    MAXIMUM = 'max'
    category = models.ForeignKey(Category, db_index=True, on_delete=models.CASCADE)
    mode = models.CharField(_('Mode'), max_length=3, choices=((MINIMUM, _('At least this number of tasks')),
                                                              (MAXIMUM, _('At most this number of tasks'))),
                            default=MAXIMUM)
    range_time_slice_days = models.IntegerField(_('Period length (days)'), default=2)
    range_time_slice_hours = models.IntegerField(_('Period length (hours)'), default=0)
    range_time_slice_seconds = models.IntegerField(_('Period length (seconds)'), default=0)

    @property
    def range_time_slice(self):
        return datetime.timedelta(days=self.range_time_slice_days, hours=self.range_time_slice_hours,
                                  seconds=self.range_time_slice_seconds)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if self.organization_id is None and self.category_id:
            self.organization_id = self.category.organization_id
        super().save(force_insert=force_insert, force_update=force_update, using=using,
                     update_fields=update_fields)

    class Meta:
        abstract = True


class MaxTaskAffectation(MaxAffectation):
    task_maximum_count = models.IntegerField(_('Number of tasks in this range'), default=1)

    class Meta:
        verbose_name = _('Number of tasks performed by an agent in a category')
        verbose_name_plural = _('Number of tasks performed by an agent in a category')


class MaxTimeTaskAffectation(MaxAffectation):
    task_maximum_time_days = models.IntegerField(_('Total task time in this range (days)'), default=1)
    task_maximum_time_hours = models.IntegerField(_('Total task time in this range (hours)'), default=0)
    task_maximum_time_seconds = models.IntegerField(_('Total task time in this range (seconds)'), default=0)

    @property
    def task_maximum_time(self):
        return datetime.timedelta(days=self.task_maximum_time_days, hours=self.task_maximum_time_hours,
                                  seconds=self.task_maximum_time_seconds)

    class Meta:
        verbose_name = _('Maximum time spent by an agent in a category')
        verbose_name_plural = _('Maximum time spent by an agent in a category')


class Task(OrganizationObject):
    orders = {'name', '-name', 'start_time', '-start_time', 'end_time', '-end_time'}
    categories = models.ManyToManyField(Category, db_index=True, blank=True)

autoplanner/templates/autoplanner/include/agent.html
{% load i18n djangofloor bootstrap3 autoplanner %}
<tr id="row_agent_{{ obj.id|my_simple_str }}">

    <td style="width: 20px;">
        <i class="fa" id="check_agent_{{ obj.id|my_simple_str }}"></i>
    </td>
    <td><form role="form" {% if obj.id is None %}onsubmit="$('#check_agent_{{ obj.id|my_simple_str }}').attr('class', 'fa fa-spin fa-spinner'); return $.df.call('autoplanner.forms.add_agent', {organization_pk: {{ organization.id|my_simple_str }}, value: serializeMArray('#row_agent_{{ obj.id|my_simple_str }}')})"{% endif %}>
        <input type="text" class="form-control" id="id_name_{{ obj.id|my_simple_str }}" name="name" {% if obj.id %}onchange="agent_u('set_agent_name', {{ obj.id|my_simple_str }}, this);"{% endif %} value="{{ obj.name }}">
    </form></td>
    <td><form role="form" {% if obj.id is None %}onsubmit="$('#check_agent_{{ obj.id|my_simple_str }}').attr('class', 'fa fa-spin fa-spinner'); return $.df.call('autoplanner.forms.add_agent', {organization_pk: {{ organization.id|my_simple_str }}, value: serializeMArray('#row_agent_{{ obj.id|my_simple_str }}')})"{% endif %}>
        {% if obj.id %}<table class="datetime">
<tr>  <td>{% trans 'Date' %}&nbsp;: <input type="text" name="start_time_0" value="{{ obj.start_time|input_date }}" class="form-control vDateField" size="10" onchange="agent_u('set_agent_start_date', {{ obj.id|my_simple_str }}, this);" onfocus="agent_u('set_agent_start_date', {{ obj.id|my_simple_str }}, this);"></td>
  <td>{% trans 'Time' %}&nbsp;: <input type="text" name="start_time_1" value="{{ obj.start_time|input_time }}" class="form-control vTimeField" size="8" onchange="agent_u('set_agent_start_time', {{ obj.id|my_simple_str }}, this);" onfocus="agent_u('set_agent_start_time', {{ obj.id|my_simple_str }}, this);"></td>
</tr></table>{% endif %}</form></td>

    <td><form role="form" {% if obj.id is None %}onsubmit="$('#check_agent_{{ obj.id|my_simple_str }}').attr('class', 'fa fa-spin fa-spinner'); return $.df.call('autoplanner.forms.add_agent', {organization_pk: {{ organization.id|my_simple_str }}, value: serializeMArray('#row_agent_{{ obj.id|my_simple_str }}')})"{% endif %}>
        {% if obj.id %}<table class="datetime">
<tr>  <td>{% trans 'Date' %}&nbsp;: <input type="text" name="end_time_0" value="{{ obj.end_time|input_date }}" class="form-control vDateField" size="10" onchange="agent_u('set_agent_end_date', {{ obj.id|my_simple_str }}, this);" onfocus="agent_u('set_agent_end_date', {{ obj.id|my_simple_str }}, this);"></td>
  <td>{% trans 'Time' %}&nbsp;: <input type="text" name="end_time_1" value="{{ obj.end_time|input_time }}" class="form-control vTimeField" size="8" onchange="agent_u('set_agent_end_time', {{ obj.id|my_simple_str }}, this);" onfocus="agent_u('set_agent_end_time', {{ obj.id|my_simple_str }}, this);"></td>
</tr></table>
        {% endif %}</form></td>

    <td>{% if obj.id %}
    <button class="btn btn-sm btn-info"
            onclick="return agent_u('show_agent_infos', {{ obj.id|my_simple_str }});">
        <i class="fa fa-plus-circle"></i>
    </button>{% else %}&nbsp;{%endif %}
    </td>
    <td>
        {% if obj.id %}<button class="btn btn-sm btn-danger" onclick="$('#check_agent_{{ obj.id|my_simple_str }}').attr('class', 'fa fa-spin fa-spinner'); return $.df.call('autoplanner.forms.remove_agent', {organization_pk: {{ organization.id|my_simple_str }}, agent_pk: {{ obj.id|my_simple_str }} })"><i class="fa fa-minus"></i></button>
        <script type="application/javascript">DateTimeShortcutsReinit('#row_agent_{{ obj.id|my_simple_str }}');</script>
        {% else %}<button class="btn btn-sm btn-success"
                          onclick="$('#check_agent_{{ obj.id|my_simple_str }}').attr('class', 'fa fa-spin fa-spinner'); return $.df.call('autoplanner.forms.add_agent', {organization_pk: {{ organization.id|my_simple_str }}, value: serializeMArray('#row_agent_{{ obj.id|my_simple_str }}')})">
        <i class="fa fa-plus"></i></button>
        {% endif %}

    </td>
</tr>

autoplanner/templates/autoplanner/include/agent_category_preference.html
{% load i18n djangofloor bootstrap3 autoplanner %}
<tr id="row_agent_category_preferences_{{ obj.id|my_simple_str }}">
    <td style="width: 20px;">
        <i class="fa" id="check_agent_category_preferences_{{ obj.id|my_simple_str }}"></i>
    </td>
    <td><form role="form" {% if obj.id is None %}onsubmit="$('#check_agent_category_preferences_{{ obj.id|my_simple_str }}').attr('class', 'fa fa-spin fa-spinner'); return $.df.call('autoplanner.forms.add_agent_category_preferences', {organization_pk: {{ organization.id|my_simple_str }}, agent_pk: {{ agent.id }}, value: serializeMArray('#row_agent_category_preferences_{{ obj.id|my_simple_str }}')});"{% endif %}>
        {% if obj.id %}<bold>{{ obj.category.name}}</bold>
    {% else %}
        <select name="category" id="id_category" class="form-control">
            {% for category in categories %}<option value="{{ category.id|my_simple_str }}">{{ category.name }}</option>{% endfor %}
        </select>
        {% endif %}
    </form></td>
    <td><form role="form" {% if obj.id is None %}onsubmit="$('#check_agent_category_preferences_{{ obj.id|my_simple_str }}').attr('class', 'fa fa-spin fa-spinner'); return $.df.call('autoplanner.forms.add_agent_category_preferences', {organization_pk: {{ organization.id|my_simple_str }}, agent_pk: {{ agent.id }}, value: serializeMArray('#row_agent_category_preferences_{{ obj.id|my_simple_str }}')});"{% endif %}>
        {% if obj.id %}<input type="number" class="form-control" id="id_affinity_{{ obj.id|my_simple_str }}" name="affinity"
               onchange="$('#check_agent_category_preferences_{{ obj.id|my_simple_str }}').attr('class', 'fa fa-spin fa-spinner'); return $.df.call('autoplanner.forms.set_agent_category_preferences_affinity', {organization_pk: {{ organization.id|my_simple_str }}, agent_category_preferences_pk: {{ obj.id|my_simple_str }}, value: $(this).serializeArray()})"
               value="{% if obj.affinity %}{{ obj.affinity|my_simple_str }}{% endif %}">{% else %}&nbsp;{% endif %}
    </form></td>
    <td><form role="form" {% if obj.id is None %}onsubmit="$('#check_agent_category_preferences_{{ obj.id|my_simple_str }}').attr('class', 'fa fa-spin fa-spinner'); return $.df.call('autoplanner.forms.add_agent_category_preferences', {organization_pk: {{ organization.id|my_simple_str }}, agent_pk: {{ agent.id }}, value: serializeMArray('#row_agent_category_preferences_{{ obj.id|my_simple_str }}')});"{% endif %}>
        {% if obj.id %}{% if obj.category.balancing_mode is None %}&nbsp;
        {% elif obj.category.balancing_mode == obj.category.BALANCE_TIME %}
        <input type="text" class="form-control" name="balancing_offset"
               onchange="$('#check_agent_category_preferences_{{ obj.id|my_simple_str }}').attr('class', 'fa fa-spin fa-spinner'); return $.df.call('autoplanner.forms.set_agent_category_preferences_balancing_offset_time', {organization_pk: {{ organization.id|my_simple_str }}, agent_category_preferences_pk: {{ obj.id|my_simple_str }}, value: $(this).serializeArray()})"
               value="{{ obj.offset_as_timedelta|timedelta }}">
        {% else %}
        <input type="number" class="form-control" name="balancing_offset"
               onchange="$('#check_agent_category_preferences_{{ obj.id|my_simple_str }}').attr('class', 'fa fa-spin fa-spinner'); return $.df.call('autoplanner.forms.set_agent_category_preferences_balancing_offset', {organization_pk: {{ organization.id|my_simple_str }}, agent_category_preferences_pk: {{ obj.id|my_simple_str }}, value: $(this).serializeArray()})"
               value="{{ obj.balancing_offset|my_simple_str }}">
        {% trans '(number of tasks)' %}
        {% endif %}{% endif %}
    </form></td>
    <td><form role="form" {% if obj.id is None %}onsubmit="$('#check_agent_category_preferences_{{ obj.id|my_simple_str }}').attr('class', 'fa fa-spin fa-spinner'); return $.df.call('autoplanner.forms.add_agent_category_preferences', {organization_pk: {{ organization.id|my_simple_str }}, agent_pk: {{ agent.id|my_simple_str }}, value: serializeMArray('#row_agent_category_preferences_{{ obj.id|my_simple_str }}')});"{% endif %}>
        {% if obj.id %}
        {% if obj.category.balancing_mode is None %}&nbsp;{% else %}
        <input type="number" class="form-control" id="id_balancing_count_{{ obj.id|my_simple_str }}" name="balancing_count"
               onchange="$('#check_agent_category_preferences_{{ obj.id|my_simple_str }}').attr('class', 'fa fa-spin fa-spinner'); return $.df.call('autoplanner.forms.set_agent_category_preferences_balancing_count', {organization_pk: {{ organization.id|my_simple_str }}, agent_category_preferences_pk: {{ obj.id|my_simple_str }}, value: $(this).serializeArray()})"
               value="{% if obj.balancing_count %}{{ obj.balancing_count|my_simple_str }}{% endif %}">
        {% endif %}{% else %}&nbsp;{% endif %}
    </form></td>
    <td>
        {% if obj.id %}<button class="btn btn-sm btn-danger" onclick="$('#check_agent_category_preferences_{{ obj.id|my_simple_str }}').attr('class', 'fa fa-spin fa-spinner'); return $.df.call('autoplanner.forms.remove_agent_category_preferences', {organization_pk: {{ organization.id|my_simple_str }}, agent_pk: {{ agent.id|my_simple_str }}, agent_category_preferences_pk: {{ obj.id|my_simple_str }} })"><i class="fa fa-minus"></i></button>
        {% else %}<button class="btn btn-sm btn-success"
                          onclick="$('#check_agent_category_preferences_{{ obj.id|my_simple_str }}').attr('class', 'fa fa-spin fa-spinner'); return $.df.call('autoplanner.forms.add_agent_category_preferences', {organization_pk: {{ organization.id|my_simple_str }}, agent_pk: {{ agent.id|my_simple_str }}, value: serializeMArray('#row_agent_category_preferences_{{ obj.id|my_simple_str }}')});">
        <i class="fa fa-plus"></i></button>
        {% endif %}
    </td>
</tr>

autoplanner/templates/autoplanner/include/agent_infos.html
{% load i18n %}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">{{ agent.name}}</h4>
</div>

<div class="modal-body">
    <p class="well">
        {% blocktrans %}Here you can modify the behaviour of the scheduler when distributing work to this resource.
        <br>
        You can consider that is fair to promote some resources, for example by giving it half the work
        compared to other resources, but only for a given type of tasks.
        {% endblocktrans %}
    </p>
    <table class="table table-stripped" id="agent_infos_{{ agent.id|my_simple_str }}-table">
        <tr>
            <th>&nbsp;</th>
            <th>{% trans 'Category' %}</th>
            <th>{% trans 'Affinity of the resource for the category' %}</th>
            <th>{% trans 'Offset' %}
                <small>{% trans 'Number of time units already done' %}</small>
            </th>
            <th>{% trans 'Balancing multiplier' %}
                <small>{% trans 'If a task of this category performed by this resource counts twice, set this number to 2.0.' %}</small>
            </th>
            <th>&nbsp;</th>
        </tr>
        {% for obj in agent_category_preferences %}
        {% include 'autoplanner/include/agent_category_preference.html' %}
        {% endfor %}
        {% if new_agent_category_preference %}
        {% with obj=new_agent_category_preference %}
        {% include 'autoplanner/include/agent_category_preference.html' %}
        {% endwith %}
        {% endif %}
    </table>

</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Close' %}</button>
</div>

autoplanner/templates/autoplanner/include/schedule.html
{% load i18n autoplanner %}<tr id="schedule_{{ obj.id|my_simple_str }}">
    <td class="schedule-status">
        {% if obj.status is None %}<i class="fa fa-spin fa-spinner"></i>
        {% elif obj.status %}<button class="btn btn-xs btn-success"><i class="fa fa-check"></i></button>
        {% else %}<button class="btn btn-xs btn-danger"><i class="fa fa-warning"></i></button>{% endif %}
    </td>
    <td class="schedule-message">
        {{ obj.message }}
    </td>
    <td class="schedule-start">
        {{ obj.celery_start }}
    </td>
    <td class="schedule-end">
        {% if obj.celery_end %}{{ obj.celery_end }}
        {% elif obj.celery_start %}{% trans 'running…' %}
        {% endif %}
    </td>
    <td class="schedule-info">
        {% if obj.is_selected %}
            <button class="btn btn-sm btn-info" onclick="return $.df.call('autoplanner.schedule.info', {organization_pk: {{ organization.id|my_simple_str }}});">&nbsp;<i class="fa fa-info"></i>&nbsp;</button>
        {% elif obj.status %}
            <button class="btn btn-sm btn-success" onclick="return $.df.call('autoplanner.schedule.apply', {organization_pk: {{ organization.id|my_simple_str }}, schedule_pk: {{ obj.id|my_simple_str }} });"> <i class="fa fa-recycle"></i></button>
        {% endif %}
    </td>
    <td class="schedule-remove">
        {% if obj.status is not None %}
        <button class="btn btn-sm btn-danger" onclick="return $.df.call('autoplanner.schedule.remove', {organization_pk: {{ organization.id|my_simple_str }}, schedule_pk: {{ obj.id|my_simple_str }} });"> <i class="fa fa-minus"></i></button>
        {% endif %}
    </td>
</tr>

autoplanner/templates/autoplanner/include/schedule_info.html
{%  load i18n l10n %}<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
            aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">{% trans 'Schedule information' %}</h4>
</div>
<div class="modal-body">
    <table class="table table-striped calendar">
        <tr>
            <th>{% trans 'Agent' %}</th>{% for category in categories %}
            <th>{{ category }}</th>{% endfor %}</tr>
        {% for agent_data in statistics %}
            <tr>
                {% for x in agent_data %}
                    <td>{% if forloop.first %}<strong>{{ x }}</strong>
                        {% else %}{% trans 'tasks: ' %}{{ x.0 }}{% trans ', total time: ' %}{{ x.1|localize }}
                                {% if x.2 %} (corrected value: {{ x.2|localize }}){% endif %}
                    {% endif %}
                    </td>{% endfor %}
            </tr>
        {% endfor %}
    </table>
</div>
<div class="modal-footer">
    <div class="btn-group">
        <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Close' %}</button>
    </div>
</div>

autoplanner/templates/autoplanner/include/schedule_status.html
{% load i18n autoplanner %}{% if organization.celery_task_id %}<i class="fa fa-spin fa-spinner"></i> {% trans 'Computation in progress…' %} <button class="btn btn-sm btn-danger" onclick="return $.df.call('autoplanner.schedule.kill', {organization_pk: {{ organization.id|my_simple_str }}, celery_task_id: '{{ organization.celery_task_id|my_simple_str }}' });">{% trans 'Interrupt' %}</button>
{% elif organization.celery_end %}<i class="fa fa-check"></i> {% trans 'Computation finished' %} <button class="btn btn-sm btn-info" onclick="return $.df.call('autoplanner.schedule.launch', {organization_pk: {{ organization.id|my_simple_str }} });">{% trans 'Again' %}</button>
{% else %}{% trans 'No computation yet.' %} <button class="btn btn-sm btn-info" onclick="return $.df.call('autoplanner.schedule.launch', {organization_pk: {{ organization.id|my_simple_str }} });">{% trans 'Compute' %}</button>
{% endif %}