autoplanner/urls.py
from django.conf.urls import url

from autoplanner import views

__author__ = 'Matthieu Gallet'
app_name = 'autoplanner'
urlpatterns = [
    url(r'^organization/(?P<organization_pk>\d+)/$', views.organization_index, name='organization_index'),

    url(r'^org/(?P<organization_pk>\d+)\.html', views.organization, name='organization'),
    url(r'^org/start/(?P<organization_pk>\d+)\.html', views.schedule_task, name='schedule_start'),
    url(r'^org/cancel/(?P<organization_pk>\d+)\.html', views.cancel_schedule_task, name='cancel_schedule'),
    url(r'^org/ical/(?P<organization_pk>\d+)/all/(?P<title>.*)\.ics', views.generate_ics, name='ical'),
    url(r'^org/ical/(?P<organization_pk>\d+)/agent/(?P<agent_pk>\d+)/(?P<title>.*)\.ics',
        views.generate_ics, name='ical'),
    url(r'^org/ical/(?P<organization_pk>\d+)/cat/(?P<category_pk>\d+)/(?P<title>.*)\.ics',
        views.generate_ics, name='ical'),
    url(r'^tasks/apply_schedule_run/(?P<schedule_run_pk>\d+)\.html', views.apply_schedule_run,
        name='apply_schedule_run'),
]

autoplanner/models.py
import datetime
import random

from django.conf import settings
from django.core.validators import RegexValidator
from django.db import models
from django.db.models import Q
from django.http import HttpRequest
from django.urls import reverse
from django.utils.formats import date_format, time_format
from django.utils.timezone import get_default_timezone
from django.utils.translation import ugettext_lazy as _

API_KEY_VARIABLE = 'api_key'

__author__ = 'Matthieu Gallet'


def default_day_start():
    x = datetime.datetime.now(tz=get_default_timezone())
    return datetime.datetime(year=x.year, month=x.month, day=x.day, hour=0, minute=0, second=0,
                             tzinfo=get_default_timezone())


def default_day_end():
    return default_day_start() + datetime.timedelta(hours=23, minutes=59, seconds=59)


def default_token(length=64, allowed_chars='abcdefghijklmnopqrstuvwxyz'
                                           'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'):
    # noinspection PyUnusedLocal
    return ''.join([random.choice(allowed_chars) for i in range(length)])


class Organization(models.Model):
    name = models.CharField(_('Name'), db_index=True, max_length=500)
    message = models.CharField(_('Message'), blank=True, max_length=500, default='')
    description = models.TextField(_('Description'), default='', blank=True)
    celery_task_id = models.CharField(_('Celery task id'), db_index=True, max_length=60, blank=True, null=True,
                                      default=None)
    celery_start = models.DateTimeField(_('Celery start'), null=True, blank=True, default=None)
    celery_end = models.DateTimeField(_('Celery end'), null=True, blank=True, default=None)
    access_token = models.CharField(_('Access token'), default=default_token, max_length=300,
                                    validators=[RegexValidator(r'^[a-zA-Z0-9]{1,300}$')])
    max_compute_time = models.PositiveIntegerField(_('Maximum time, in seconds, for finding a solution'),
                                                   default=None, blank=True, null=True,
                                                   help_text=_('Leave it blank if you do not want to set a limit'))
    admins = models.ManyToManyField(settings.AUTH_USER_MODEL, db_index=True, verbose_name=_('Administrators'))
    current_schedule = models.ForeignKey('ScheduleRun', default=None, blank=True, null=True, db_index=True,
                                         related_name='current_organizations', on_delete=models.SET_NULL)

    @classmethod
    def query(cls, request: HttpRequest, readonly=False):
        access_token = ''
        user = getattr(request, 'user')
        if hasattr(request, 'GET'):
            # noinspection PyCallByClass,PyTypeChecker
            access_token = request.GET.get(API_KEY_VARIABLE, '')
        if not user or user.is_anonymous:
            return cls.objects.filter(access_token=access_token)
        # noinspection PyUnresolvedReferences
        elif user.is_superuser:
            return cls.objects.all()
        elif readonly:
            # noinspection PyUnresolvedReferences
            return cls.objects.filter(Q(admins=user) | Q(access_token=access_token))
        # noinspection PyUnresolvedReferences
        return cls.objects.filter(admins=user)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return '%s?%s=%s' % (reverse('organization', kwargs={'organization_pk': self.pk}),
                             API_KEY_VARIABLE, self.access_token)


class ScheduleRun(models.Model):
    organization = models.ForeignKey(Organization, db_index=True, on_delete=models.CASCADE)
    status = models.NullBooleanField(_('Is valid?'), db_index=True, default=None)
    is_selected = models.BooleanField(_('Selected?'), db_index=True, default=False)
    message = models.TextField(_('Result'), max_length=500, default='', blank=True)
    celery_task_id = models.CharField(_('Celery task id'), db_index=True, max_length=60, blank=True, null=True,
                                      default=None)
    celery_start = models.DateTimeField(_('Computation start'), null=True, blank=True, default=None)
    celery_end = models.DateTimeField(_('Computation end'), null=True, blank=True, default=None)
    process_id = models.IntegerField(_('Process ID'), db_index=True, blank=True, null=True, default=None)
    result_dict = models.TextField(_('JSON-serialized result'), blank=True, default=None, null=True)

    def __str__(self):
        end = self.celery_end
        if not end:
            return str(_('Not finished yet.'))
        return '%(d)s, %(t)s' % {'d': date_format(end, use_l10n=True), 't': time_format(end, use_l10n=True)}

    def __unicode__(self):
        return self.__str__()


class OrganizationObject(models.Model):
    organization = models.ForeignKey(Organization, db_index=True, on_delete=models.CASCADE)

    class Meta(object):
        abstract = True

    @classmethod
    def query(cls, request: HttpRequest):
        # noinspection PyUnresolvedReferences
        if request.user.is_superuser:
            return cls.objects.all()
        # noinspection PyUnresolvedReferences
        return cls.objects.filter(organization__admins=request.user)


class Agent(OrganizationObject):
    name = models.CharField(_('Name'), db_index=True, max_length=500)
    start_time = models.DateTimeField(_('Arrival time'), db_index=True, default=None, blank=True, null=True,
                                      help_text=_('Before this date, the agent cannot perform'
                                                  'any task.'))
    end_time = models.DateTimeField(_('Leaving time'), db_index=True, default=None, blank=True, null=True,
                                    help_text=_('After this date, the agent cannot perform any task.'))

    class Meta(object):
        ordering = ('name',)

    def __str__(self):
        return self.name


class Category(OrganizationObject):
    BALANCE_TIME = 'time'
    BALANCE_NUMBER = 'number'
    name = models.CharField(_('Name'), db_index=True, max_length=500)
    balancing_mode = models.CharField(_('Balancing mode'),
                                      max_length=10, choices=((None, _('No balancing')),
                                                              (BALANCE_TIME, _('Total task time')),
                                                              (BALANCE_NUMBER, _('Total task number'))),
                                      blank=True, null=True, default=None)
    balancing_tolerance = models.FloatField(_('Tolerance for balancing the total duration (in seconds)|tasks '
                                              'across agents'), default=0., blank=True, null=True)
    auto_affinity = models.FloatField(_('Affinity for allocating successive tasks of the same category '
                                        'to the same agent'), default=0., blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Category of tasks')
        verbose_name_plural = _('Categories of tasks')

    @property
    def balancing_tolerance_as_timedelta_2(self):
        return datetime.timedelta(seconds=(self.balancing_tolerance or 0))

    @property
    def balancing_tolerance_2(self):
        return self.balancing_tolerance or 0


class MaxAffectation(OrganizationObject):
    MINIMUM = 'min'
    MAXIMUM = 'max'
    category = models.ForeignKey(Category, db_index=True, on_delete=models.CASCADE)
    mode = models.CharField(_('Mode'), max_length=3, choices=((MINIMUM, _('At least this number of tasks')),
                                                              (MAXIMUM, _('At most this number of tasks'))),
                            default=MAXIMUM)
    range_time_slice_days = models.IntegerField(_('Period length (days)'), default=2)
    range_time_slice_hours = models.IntegerField(_('Period length (hours)'), default=0)
    range_time_slice_seconds = models.IntegerField(_('Period length (seconds)'), default=0)

    @property
    def range_time_slice(self):
        return datetime.timedelta(days=self.range_time_slice_days, hours=self.range_time_slice_hours,
                                  seconds=self.range_time_slice_seconds)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if self.organization_id is None and self.category_id:
            self.organization_id = self.category.organization_id
        super().save(force_insert=force_insert, force_update=force_update, using=using,
                     update_fields=update_fields)

    class Meta:
        abstract = True


class MaxTaskAffectation(MaxAffectation):
    task_maximum_count = models.IntegerField(_('Number of tasks in this range'), default=1)

    class Meta:
        verbose_name = _('Number of tasks performed by an agent in a category')
        verbose_name_plural = _('Number of tasks performed by an agent in a category')


class MaxTimeTaskAffectation(MaxAffectation):
    task_maximum_time_days = models.IntegerField(_('Total task time in this range (days)'), default=1)
    task_maximum_time_hours = models.IntegerField(_('Total task time in this range (hours)'), default=0)
    task_maximum_time_seconds = models.IntegerField(_('Total task time in this range (seconds)'), default=0)

    @property
    def task_maximum_time(self):
        return datetime.timedelta(days=self.task_maximum_time_days, hours=self.task_maximum_time_hours,
                                  seconds=self.task_maximum_time_seconds)

    class Meta:
        verbose_name = _('Maximum time spent by an agent in a category')
        verbose_name_plural = _('Maximum time spent by an agent in a category')


class Task(OrganizationObject):
    orders = {'name', '-name', 'start_time', '-start_time', 'end_time', '-end_time'}
    categories = models.ManyToManyField(Category, db_index=True, blank=True)

autoplanner/templates/autoplanner/tabs/agents.html
{% load i18n bootstrap3 %}
<p class="well">{% blocktrans %}You must define some resources to perform the existing tasks.
    A single resource can perform simultaneous tasks as soon they belong to different categories.
{% endblocktrans %}
</p>

<table class="table table-striped" id="resource-table">
    <tr>
        <th>&nbsp;</th>
        <th>{% trans 'Name' %}</th>
        <th>{% trans 'Arrival time?' %}</th>
        <th>{% trans 'Leaving time?' %}</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
    </tr>
    {% for obj in agents %}
    {% include 'autoplanner/include/agent.html' %}
    {% endfor %}
    {% with obj=new_agent %}
    {% include 'autoplanner/include/agent.html' %}
    {% endwith %}
</table>

autoplanner/templates/autoplanner/tabs/balancing.html
{% load i18n %}

<p class="well">{% blocktrans %}You can add some constraints to obtain a better schedule.

    You can limit the total time passed by a given resource on tasks of a given type,
    or on the contrary ensures that any resource processes at least a certain number of tasks of another kind.
    {% endblocktrans %}</p>

<table class="table table-striped" id="max-task-affectation-table">
    <tr>
        <th>&nbsp;</th>
        <th>{% trans 'At most or at least…' %}</th>
        <th>{% trans 'this number…' %}</th>
        <th>{% trans 'of tasks of category…' %}</th>
        <th>{% trans 'within this period' %}</th>
        <th>&nbsp;</th>
    </tr>
    {% for obj in max_task_affectations %}
    {% include 'autoplanner/include/max_task_affectation.html' %}
    {% endfor %}
    {% with obj=new_max_task_affectation %}
    {% include 'autoplanner/include/max_task_affectation.html' %}
    {% endwith %}
</table>


<table class="table table-striped" id="max-time-affectation-table">
    <tr>
        <th>&nbsp;</th>
        <th>{% trans 'At most or at least…' %}</th>
        <th>{% trans 'this time…' %}</th>
        <th>{% trans 'on tasks of category…' %}</th>
        <th>{% trans 'within this period' %}</th>
        <th>&nbsp;</th>
    </tr>
    {% for obj in max_time_affectations %}
    {% include 'autoplanner/include/max_time_affectation.html' %}
    {% endfor %}
    {% with obj=new_max_time_affectation %}
    {% include 'autoplanner/include/max_time_affectation.html' %}
    {% endwith %}
</table>

autoplanner/templates/autoplanner/tabs/categories.html
{% load i18n %}
<p class="well">{% blocktrans %}To ensure that two overlapping tasks are assigned to different resources,
    they must belong to the same category.
<br>
    Schedule takes into account the balance of tasks before dispatching them to resources. However, you can only define
    one type of balancing for each type of tasks: balancing the total time used by each resource, or the number of tasks
    made by each resource.
    {% endblocktrans %}</p>
<table class="table table-striped" id="category-table">
    <tr>
        <th>&nbsp;</th>
        <th>{% trans 'Name' %}</th>
        <th>{% trans 'How to balance tasks of this category accross resources?' %}</th>
        <th>{% trans 'Which difference do you tolerate between the least and the most used resources?' %}</th>
        <th>{% trans 'Bonus given when two successive tasks are assigned to the same resource?' %}</th>
        <th>&nbsp;</th>
    </tr>
    {% for obj in categories %}
    {% include 'autoplanner/include/category.html' %}
    {% endfor %}
    {% with obj=new_category %}
    {% include 'autoplanner/include/category.html' %}
    {% endwith %}
<script>
    function debug(obj) {
        console.warn(obj);
        console.warn($(obj + ' form').serializeArray());
        console.warn($(obj + ' form'));
        console.warn($(obj));
        console.warn($(obj).serializeArray());

    }

</script>
</table>

autoplanner/templates/autoplanner/tabs/general.html
{% load i18n djangofloor autoplanner %}
<h1>{{ organization.name }}</h1>

<form role="form">
  <div class="form-group">
    <label for="id_description">{% trans 'Description' %}</label>
    <span class="pull-right"><i class="fa" id="check_description"></i></span>
    <textarea class="form-control" id="id_description" name="description" onchange="$('#check_description').attr('class', 'fa fa-spin fa-spinner'); return $.df.call('autoplanner.forms.set_description', {organization_pk: {{ organization.id|my_simple_str }}, value: $(this).serializeArray()})">{{ organization.description }}</textarea>
  </div>
  <div class="form-group">
    <label for="id_access_token">{% trans 'Access token' %}</label>
    <button class="btn btn-info btn-xs" onclick="$('#check_access_token').attr('class', 'fa fa-spin fa-spinner'); return $.df.call('autoplanner.forms.new_access_token', {organization_pk: {{ organization.id|my_simple_str }} })">{% trans 'New token' %}</button>
    <span class="pull-right">
    <i class="fa" id="check_access_token"></i>
    </span>
    <input type="text" class="form-control" id="id_access_token" name="access_token" onchange="$('#check_access_token').attr('class', 'fa fa-spin fa-spinner'); return $.df.call('autoplanner.forms.set_access_token', {organization_pk: {{ organization.id|my_simple_str }}, value: $(this).serializeArray()})" value="{{ organization.access_token }}">
  </div>
  <div class="form-group">
    <label for="id_max_compute_time">{% trans 'Max computation time for finding schedules, in seconds' %}</label>
    <span class="pull-right">
    <i class="fa" id="check_max_compute_time"></i>
    </span>
    <input type="number" class="form-control" id="id_max_compute_time" name="max_compute_time" onchange="$('#check_max_compute_time').attr('class', 'fa fa-spin fa-spinner'); return $.df.call('autoplanner.forms.set_max_compute_time', {organization_pk: {{ organization.id|my_simple_str }}, value: $(this).serializeArray()})" value="{% if organization.max_compute_time %}{{ organization.max_compute_time|my_simple_str }}{% endif %}">
  </div>
</form>

autoplanner/templates/autoplanner/tabs/schedule.html
{% load i18n l10n autoplanner %}
<div class="help-block form-group"></div>
<div class="text-center"><div class="btn-group">
<button onclick="return false;" class="btn btn-sm btn-default">{% trans 'Abstract' %}</button>
<button onclick="return $.df.call('autoplanner.calendar.month', {organization_pk: {{ organization.id|my_simple_str }} });" class="btn btn-sm btn-info">{% trans 'By month' %}</button>
<button onclick="return $.df.call('autoplanner.calendar.week', {organization_pk: {{ organization.id|my_simple_str }} });" class="btn btn-sm btn-info">{% trans 'By week' %}</button>
</div></div>
<div class="help-block form-group"></div>
<table class="table table-striped calendar">
    <tr><th>{% trans 'Calendar' %}</th><th>{% trans 'Agent' %}</th>{% for category in categories %}<th>{{ category }} <small><a href="{% url 'ical' organization_pk=obj.pk category_pk=category.pk title=category.name %}?{{ api_key_variable }}={{ obj.access_token }}">{% trans 'iCal' %}</a></small></th>{% endfor %}</tr>
{% for agent_data in statistics %}<tr>
<td><a href="{% url 'ical' organization_pk=obj.pk agent_pk=agent_data.0.pk title=agent_data.0.name %}?{{ api_key_variable }}={{ obj.access_token }}">{% trans 'iCal' %}</a></td>
{% for x in agent_data %}<td>{% if forloop.first %}<strong>{{ x }}</strong>
{% else %}{% trans 'tasks: ' %}{{ x.0 }}{% trans ', total time: ' %}{{ x.1|localize }}{% if x.2 %} (corrected value: {{ x.2|localize }}){% endif %}
{% endif %}
</td>{% endfor %}
</tr>
{% endfor %}
</table>

autoplanner/templates/autoplanner/tabs/schedules.html
{% load i18n %}
<p class="well">{% blocktrans %}Here is the list of computed schedules.
<br>
    By default, only the last valid schedule is loaded, but you can reload any previous schedule.

Only the ability of assignment of all tasks to resources (and the non-overlapping of tasks) is checked.
So, if you added extra constraints or if you changed the balancing rules, then they can be broken by the loaded schedule.
    {% endblocktrans %}</p>
<table class="table table-striped" id="schedules-table">
    <tr id="schedules-header">
        <th>{% trans 'Is valid?' %}</th>
        <th>{% trans 'Result' %}</th>
        <th>{% trans 'Start time' %}</th>
        <th>{% trans 'End time' %}</th>
        <th>{% trans 'Select it' %}</th>
        <th>&nbsp;</th>
    </tr>
    {% for obj in schedules %}
    {% include 'autoplanner/include/schedule.html' %}
    {% endfor %}
</table>

autoplanner/templates/autoplanner/tabs/tasks.html
{% load i18n bootstrap3 autoplanner %}
<div class="row">
    <div class="col-md-10 col-lg-10 col-sm-12">
        <p class="well">{% blocktrans %}Finally, you need to define your tasks.

            The schedule will determine how to dispatch them to resources will respecting your constraints, if such a
            solution exists.
            <br>If you assign a task to a specific resource, then the scheduler will not change its assignment.
            The scheduler will only propose assignments for all tasks.{% endblocktrans %}
        </p>
        <small><span class="datetimeshortcuts"><a href="#" onclick="return callTask(undefined, undefined, undefined, undefined, 'autoplanner.forms.task_import');">{% trans 'Import multiple tasks' %}</a> </span> </small>

        <table class="table table-striped" id="tasks_table">
            <tr>
                <th><small><span class="datetimeshortcuts"><a href="#" onclick="return InverseSelection();">{% trans 'Select' %}</a></span></small></th>
                <th>{% trans 'The task…' %}</th>
                <th>{% trans 'begins at…' %}</th>
                <th>{% trans 'and ends at…' %}</th>
                <th>{% trans 'belongs to…' %}</th>
                <th>{% trans 'and is assigned to:' %}</th>
                <th colspan="2">
                    <small><span class="datetimeshortcuts"><a href="#" onclick="return $.df.call('autoplanner.forms.task_multiple_update_show', {organization_pk: {{ organization.id|my_simple_str }} });">{% trans 'Update selection' %}</a> </span> </small>
                </th>
            </tr>
            <tr>
                <td colspan="7">
                    <input class="form-control" value="{{ pattern }}" onchange="return callTask(undefined, undefined, undefined, this.value);" onsubmit="return callTask(undefined, undefined, undefined, this.value);" placeholder="{% trans 'Filter…' %}">
                </td>
            </tr>
            {% with obj=new_task obj_categories=empty_set %}
            {% include 'autoplanner/include/task.html' %}
            {% endwith %}
        </table>
    </div>
    <div class="col-md-2 col-lg-2 col-sm-12">
        <ul class="list-group">
            <li class="list-group-item active">{% trans 'By category' %}</li>
            <li id="by_category_None" class="filter-tasks list-group-item {% if category_id is None %}active{% endif %}"><a href="#" onclick="return callTask(undefined, undefined, null);">{% trans 'all categories' %}</a></li>
            {% for x in categories %}
            <li id="by_category_{{ x.id|my_simple_str }}" class="filter-tasks list-group-item {% if x.id == category_id %}active{% endif %}"><a href="#" onclick="return callTask(undefined, undefined, {{ x.id|my_simple_str }});">{{ x.name }}</a></li>
            {% endfor %}
        </ul>
        <ul class="list-group">
            <li class="list-group-item active">{% trans 'By agent' %}</li>
            <li id="by_agent_None" class="filter-tasks list-group-item {% if agent_id is None %}active{% endif %}"><a href="#" onclick="return callTask(undefined, null);">{% trans 'all agents' %}</a></li>
            {% for x in agents %}
            <li id="by_agent_{{ x.id|my_simple_str }}" class="filter-tasks list-group-item {% if x.id == agent_id %}active{% endif %}"><a href="#" onclick="callTask(undefined, {{ x.id|my_simple_str }});">{{ x.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
</div>
<script type="application/javascript">
function callTask(order_by, agent_id, category_id, pattern, signal, kwargs) {
    if (kwargs === undefined) kwargs = {}; 
    kwargs.organization_pk = {{ organization.id|my_simple_str }};
    kwargs.order_by = order_by === undefined ? {{ order_by|js_value }} : order_by;
    kwargs.pattern = pattern === undefined ? {{ pattern|js_value }} : pattern;
    kwargs.agent_id = agent_id === undefined ? {{ agent_id|js_value }} : agent_id;
    kwargs.category_id = category_id === undefined ? {{ category_id|js_value }} : category_id;
    if (signal === undefined) signal = 'autoplanner.forms.filter_tasks';
    return $.df.call(signal, kwargs);
}
</script>