autoplanner/urls.py
from django.conf.urls import url

from autoplanner import views

__author__ = 'Matthieu Gallet'
app_name = 'autoplanner'
urlpatterns = [
    url(r'^organization/(?P<organization_pk>\d+)/$', views.organization_index, name='organization_index'),

    url(r'^org/(?P<organization_pk>\d+)\.html', views.organization, name='organization'),
    url(r'^org/start/(?P<organization_pk>\d+)\.html', views.schedule_task, name='schedule_start'),
    url(r'^org/cancel/(?P<organization_pk>\d+)\.html', views.cancel_schedule_task, name='cancel_schedule'),
    url(r'^org/ical/(?P<organization_pk>\d+)/all/(?P<title>.*)\.ics', views.generate_ics, name='ical'),
    url(r'^org/ical/(?P<organization_pk>\d+)/agent/(?P<agent_pk>\d+)/(?P<title>.*)\.ics',
        views.generate_ics, name='ical'),
    url(r'^org/ical/(?P<organization_pk>\d+)/cat/(?P<category_pk>\d+)/(?P<title>.*)\.ics',
        views.generate_ics, name='ical'),
    url(r'^tasks/apply_schedule_run/(?P<schedule_run_pk>\d+)\.html', views.apply_schedule_run,
        name='apply_schedule_run'),
]

autoplanner/models.py
import datetime
import random

from django.conf import settings
from django.core.validators import RegexValidator
from django.db import models
from django.db.models import Q
from django.http import HttpRequest
from django.urls import reverse
from django.utils.formats import date_format, time_format
from django.utils.timezone import get_default_timezone
from django.utils.translation import ugettext_lazy as _

API_KEY_VARIABLE = 'api_key'

__author__ = 'Matthieu Gallet'


def default_day_start():
    x = datetime.datetime.now(tz=get_default_timezone())
    return datetime.datetime(year=x.year, month=x.month, day=x.day, hour=0, minute=0, second=0,
                             tzinfo=get_default_timezone())


def default_day_end():
    return default_day_start() + datetime.timedelta(hours=23, minutes=59, seconds=59)


def default_token(length=64, allowed_chars='abcdefghijklmnopqrstuvwxyz'
                                           'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'):
    # noinspection PyUnusedLocal
    return ''.join([random.choice(allowed_chars) for i in range(length)])


class Organization(models.Model):
    name = models.CharField(_('Name'), db_index=True, max_length=500)
    message = models.CharField(_('Message'), blank=True, max_length=500, default='')
    description = models.TextField(_('Description'), default='', blank=True)
    celery_task_id = models.CharField(_('Celery task id'), db_index=True, max_length=60, blank=True, null=True,
                                      default=None)
    celery_start = models.DateTimeField(_('Celery start'), null=True, blank=True, default=None)
    celery_end = models.DateTimeField(_('Celery end'), null=True, blank=True, default=None)
    access_token = models.CharField(_('Access token'), default=default_token, max_length=300,
                                    validators=[RegexValidator(r'^[a-zA-Z0-9]{1,300}$')])
    max_compute_time = models.PositiveIntegerField(_('Maximum time, in seconds, for finding a solution'),
                                                   default=None, blank=True, null=True,
                                                   help_text=_('Leave it blank if you do not want to set a limit'))
    admins = models.ManyToManyField(settings.AUTH_USER_MODEL, db_index=True, verbose_name=_('Administrators'))
    current_schedule = models.ForeignKey('ScheduleRun', default=None, blank=True, null=True, db_index=True,
                                         related_name='current_organizations', on_delete=models.SET_NULL)

    @classmethod
    def query(cls, request: HttpRequest, readonly=False):
        access_token = ''
        user = getattr(request, 'user')
        if hasattr(request, 'GET'):
            # noinspection PyCallByClass,PyTypeChecker
            access_token = request.GET.get(API_KEY_VARIABLE, '')
        if not user or user.is_anonymous:
            return cls.objects.filter(access_token=access_token)
        # noinspection PyUnresolvedReferences
        elif user.is_superuser:
            return cls.objects.all()
        elif readonly:
            # noinspection PyUnresolvedReferences
            return cls.objects.filter(Q(admins=user) | Q(access_token=access_token))
        # noinspection PyUnresolvedReferences
        return cls.objects.filter(admins=user)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return '%s?%s=%s' % (reverse('organization', kwargs={'organization_pk': self.pk}),
                             API_KEY_VARIABLE, self.access_token)


class ScheduleRun(models.Model):
    organization = models.ForeignKey(Organization, db_index=True, on_delete=models.CASCADE)
    status = models.NullBooleanField(_('Is valid?'), db_index=True, default=None)
    is_selected = models.BooleanField(_('Selected?'), db_index=True, default=False)
    message = models.TextField(_('Result'), max_length=500, default='', blank=True)
    celery_task_id = models.CharField(_('Celery task id'), db_index=True, max_length=60, blank=True, null=True,
                                      default=None)
    celery_start = models.DateTimeField(_('Computation start'), null=True, blank=True, default=None)
    celery_end = models.DateTimeField(_('Computation end'), null=True, blank=True, default=None)
    process_id = models.IntegerField(_('Process ID'), db_index=True, blank=True, null=True, default=None)
    result_dict = models.TextField(_('JSON-serialized result'), blank=True, default=None, null=True)

    def __str__(self):
        end = self.celery_end
        if not end:
            return str(_('Not finished yet.'))
        return '%(d)s, %(t)s' % {'d': date_format(end, use_l10n=True), 't': time_format(end, use_l10n=True)}

    def __unicode__(self):
        return self.__str__()


class OrganizationObject(models.Model):
    organization = models.ForeignKey(Organization, db_index=True, on_delete=models.CASCADE)

    class Meta(object):
        abstract = True

    @classmethod
    def query(cls, request: HttpRequest):
        # noinspection PyUnresolvedReferences
        if request.user.is_superuser:
            return cls.objects.all()
        # noinspection PyUnresolvedReferences
        return cls.objects.filter(organization__admins=request.user)


class Agent(OrganizationObject):
    name = models.CharField(_('Name'), db_index=True, max_length=500)
    start_time = models.DateTimeField(_('Arrival time'), db_index=True, default=None, blank=True, null=True,
                                      help_text=_('Before this date, the agent cannot perform'
                                                  'any task.'))
    end_time = models.DateTimeField(_('Leaving time'), db_index=True, default=None, blank=True, null=True,
                                    help_text=_('After this date, the agent cannot perform any task.'))

    class Meta(object):
        ordering = ('name',)

    def __str__(self):
        return self.name


class Category(OrganizationObject):
    BALANCE_TIME = 'time'
    BALANCE_NUMBER = 'number'
    name = models.CharField(_('Name'), db_index=True, max_length=500)
    balancing_mode = models.CharField(_('Balancing mode'),
                                      max_length=10, choices=((None, _('No balancing')),
                                                              (BALANCE_TIME, _('Total task time')),
                                                              (BALANCE_NUMBER, _('Total task number'))),
                                      blank=True, null=True, default=None)
    balancing_tolerance = models.FloatField(_('Tolerance for balancing the total duration (in seconds)|tasks '
                                              'across agents'), default=0., blank=True, null=True)
    auto_affinity = models.FloatField(_('Affinity for allocating successive tasks of the same category '
                                        'to the same agent'), default=0., blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Category of tasks')
        verbose_name_plural = _('Categories of tasks')

    @property
    def balancing_tolerance_as_timedelta_2(self):
        return datetime.timedelta(seconds=(self.balancing_tolerance or 0))

    @property
    def balancing_tolerance_2(self):
        return self.balancing_tolerance or 0


class MaxAffectation(OrganizationObject):
    MINIMUM = 'min'
    MAXIMUM = 'max'
    category = models.ForeignKey(Category, db_index=True, on_delete=models.CASCADE)
    mode = models.CharField(_('Mode'), max_length=3, choices=((MINIMUM, _('At least this number of tasks')),
                                                              (MAXIMUM, _('At most this number of tasks'))),
                            default=MAXIMUM)
    range_time_slice_days = models.IntegerField(_('Period length (days)'), default=2)
    range_time_slice_hours = models.IntegerField(_('Period length (hours)'), default=0)
    range_time_slice_seconds = models.IntegerField(_('Period length (seconds)'), default=0)

    @property
    def range_time_slice(self):
        return datetime.timedelta(days=self.range_time_slice_days, hours=self.range_time_slice_hours,
                                  seconds=self.range_time_slice_seconds)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if self.organization_id is None and self.category_id:
            self.organization_id = self.category.organization_id
        super().save(force_insert=force_insert, force_update=force_update, using=using,
                     update_fields=update_fields)

    class Meta:
        abstract = True


class MaxTaskAffectation(MaxAffectation):
    task_maximum_count = models.IntegerField(_('Number of tasks in this range'), default=1)

    class Meta:
        verbose_name = _('Number of tasks performed by an agent in a category')
        verbose_name_plural = _('Number of tasks performed by an agent in a category')


class MaxTimeTaskAffectation(MaxAffectation):
    task_maximum_time_days = models.IntegerField(_('Total task time in this range (days)'), default=1)
    task_maximum_time_hours = models.IntegerField(_('Total task time in this range (hours)'), default=0)
    task_maximum_time_seconds = models.IntegerField(_('Total task time in this range (seconds)'), default=0)

    @property
    def task_maximum_time(self):
        return datetime.timedelta(days=self.task_maximum_time_days, hours=self.task_maximum_time_hours,
                                  seconds=self.task_maximum_time_seconds)

    class Meta:
        verbose_name = _('Maximum time spent by an agent in a category')
        verbose_name_plural = _('Maximum time spent by an agent in a category')


class Task(OrganizationObject):
    orders = {'name', '-name', 'start_time', '-start_time', 'end_time', '-end_time'}
    categories = models.ManyToManyField(Category, db_index=True, blank=True)

autoplanner/templates/autoplanner/base.html
{% extends 'djangofloor/bootstrap3/base.html' %}

autoplanner/templates/autoplanner/categories.html
<table>

</table>

autoplanner/templates/autoplanner/index.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="container">
<ul>{% for organization in organizations %}
    <li><a href="{% url 'organization' organization.pk %}">{{ organization }}</a></li>
{% endfor %}
</ul>
    </div>
{% endblock %}

autoplanner/templates/autoplanner/organization.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls admin_static admin_modify l10n %}
{% block extrahead %}{{ block.super }}
    <script type="text/javascript" src="{% url 'jsi18n' %}"></script>
    {{ media }}
{% endblock %}

{% block extrastyle %}{{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}"/>{% endblock %}

{% block coltype %}colM{% endblock %}

{% block bodyclass %}{{ block.super }} app-{{ opts.app_label }} model-{{ opts.model_name }} change-form{% endblock %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
        <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
        &rsaquo; <a href="{% url 'admin:app_list' app_label=opts.app_label %}">{{ opts.app_config.verbose_name }}</a>
        &rsaquo; {% if has_change_permission %}
        <a href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural|capfirst }}</a>{% else %}
        {{ opts.verbose_name_plural|capfirst }}{% endif %}
        &rsaquo; {% if add %}{% trans 'Repeat task' %} {{ opts.verbose_name }}{% else %}
        {{ original|truncatewords:"18" }}{% endif %}
    </div>
{% endblock %}

{% block content %}
    <div id="content-main">
    <h1>{{ obj.name }}</h1>
    <p>{{ description|safe }}</p>
<table>
    <tr><th>{% trans 'Calendar' %}</th><th>{% trans 'Agent' %}</th>{% for category in categories %}<th>{{ category }} <small><a href="{% url 'ical' organization_pk=obj.pk category_pk=category.pk title=category.name %}?{{ api_key_variable }}={{ obj.access_token }}">{% trans 'iCal' %}</a></small></th>{% endfor %}</tr>
{% for agent_data in statistics %}<tr>
<td><a href="{% url 'ical' organization_pk=obj.pk agent_pk=agent_data.0.pk title=agent_data.0.name %}?{{ api_key_variable }}={{ obj.access_token }}">{% trans 'iCal' %}</a></td>
{% for x in agent_data %}<td>{% if forloop.first %}<strong>{{ x }}</strong>

{% else %}{% trans 'tasks: ' %}{{ x.0 }}{% trans ', total time: ' %}{{ x.1|localize }}{% if x.2 %} (corrected value: {{ x.2|localize }}){% endif %}
{% endif %}
</td>{% endfor %}
</tr>
{% endfor %}

</table>

    </div>
<p class="changelink-box"><a href="{% url 'ical' organization_pk=obj.pk title=obj.name %}?{{ api_key_variable }}={{ obj.access_token }}" class="changelink">{% trans 'Global calendar (.ics)' %}</a></p>
<div class="submit-row">

    <p class="changelink-box"><a href="{% url 'admin:autoplanner_organization_change' obj.pk %}" class="changelink">{% trans 'Modify' %}</a></p>
</div>
{% endblock %}

autoplanner/templates/autoplanner/organization_index.html
{% extends 'autoplanner/base.html' %}
{% load bootstrap3 i18n autoplanner %}

{% block body-container %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-1 col-lg-1 col-sm-1">
        </div>
        <div class="col-md-10 col-lg-10 col-sm-10">
            <p id="organization_message"></p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-1 col-lg-1 col-sm-1">
        </div>
        <div class="col-md-10 col-lg-10 col-sm-10">

            <ul class="nav nav-tabs" id="global_tabs">
                <li><a id="a_general" class="main_tabs" href="#general" data-toggle="tab">{% trans 'General' %}</a></li>
                <li><a id="a_schedule" class="main_tabs" href="#schedule" data-toggle="tab">{% trans 'Schedule' %}</a></li>
                <li><a id="a_categories" class="main_tabs" href="#categories" data-toggle="tab">{% trans 'Categories' %}</a></li>
                <li><a id="a_agents" class="main_tabs" href="#agents" data-toggle="tab">{% trans 'Resources' %}</a></li>
                <li><a id="a_balancing" class="main_tabs" href="#balancing" data-toggle="tab">{% trans 'Constraints' %}</a></li>
                <li><a id="a_tasks" class="main_tabs" href="#tasks" data-toggle="tab">{% trans 'Tasks' %}</a></li>
                <li><a id="a_schedules" class="main_tabs" href="#schedules" data-toggle="tab">{% trans 'Schedules' %}</a></li>
            </ul></div>
    </div>
    <div class="row">
        <div class="col-md-1 col-lg-1 col-sm-1">
        </div>
        <div class="col-md-10 col-lg-10 col-sm-10">
        <span class="center" id="schedule_status">{% include 'autoplanner/include/schedule_status.html' %}</span>
        </div>
    </div>
    <div class="row">
        <div class="col-md-1 col-lg-1 col-sm-1">
        </div>
        <div class="col-md-10 col-lg-10 col-sm-10">

            <div class="tab-content">
                <div class="tab-pane active" id="general">...</div>
                <div class="tab-pane" id="schedule">...</div>
                <div class="tab-pane" id="balancing">...</div>
                <div class="tab-pane" id="categories">...</div>
                <div class="tab-pane" id="agents">...</div>
                <div class="tab-pane" id="tasks">...</div>
                <div class="tab-pane" id="schedules">...</div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="{% url 'jsi18n' %}"></script>
{% endblock %}

{% block scripts %}

<script type="application/javascript">
    django.jQuery = $;
    $(function () {
        $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
            $.df.call('autoplanner.change_tab', {organization_pk: {{ organization.id|my_simple_str }}, tab_name: e.target.id.substr(2)});
        });
        $('#global_tabs a:first').tab('show')
    });
    function agent_u(signal_name, obj_id, form) {
        $('#check_agent_' + obj_id).attr('class', 'fa fa-spin fa-spinner');
        if(form) {
            $.df.call('autoplanner.forms.' + signal_name, {organization_pk: {{ organization.id|my_simple_str }}, agent_pk: obj_id, value: $(form).serializeArray()});
        }
        else {
            $.df.call('autoplanner.forms.' + signal_name, {organization_pk: {{ organization.id|my_simple_str }}, agent_pk: obj_id});
        }
        return false;
    }
    function task_u(signal_name, obj_id, rowId) {
        if(rowId) {
            var values = serializeMArray(rowId);
            $('#check_task_' + obj_id).attr('class', 'fa fa-spin fa-spinner');
            $.df.call('autoplanner.forms.' + signal_name, {organization_pk: {{ organization.id|my_simple_str }}, task_pk: obj_id, value: values});
        }
        else {
            $.df.call('autoplanner.forms.' + signal_name, {organization_pk: {{ organization.id|my_simple_str }}, task_pk: obj_id});
        }
        return false;
    }
</script>
{% endblock %}

autoplanner/templates/autoplanner/organizations.html
{% extends 'autoplanner/base.html' %}
{% load bootstrap3 i18n autoplanner %}

{% block body-container %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-1 col-lg-1 col-sm-1">
        </div>
        <div class="col-md-10 col-lg-10 col-sm-10">
            <h1>{% trans 'Current organizations' %}</h1>
            <ul class="list-unstyled">
                {% for obj in organizations %}
                <li>
                <h3>{{ obj.name }} <small><a href="{% url 'organization_index' organization_pk=obj.pk %}">{% trans 'Modify' %}</a></small></h3>
                {%  if obj.description %}
                <div class="well no-padding">{{ obj.description|markdown }}</div>
                {%  endif %}
                </li>
                {% endfor %}
            {% if perms.autoplanner.add_organization %}
            <li>
                <h2>{% trans 'New organization' %}</h2>
                <div class="panel panel-info"><div class="panel-heading">{%  trans 'Create a new organization' %}</div>
            <form method="post" action="?" class="panel-body">
                {%  bootstrap_form form %}
                <input class="btn btn-sm btn-info" value="{% trans 'Create!' %}" type="submit">
                {% csrf_token %}
            </form></div>
            </li>
            {%  endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}